### ISSUE TITLE
model.findAndCountAll is not a function

### ISSUE THREAD

**Issue by alfianakbar** [lalalilo/express-sequelize-crud#42]
Hi,
I got this error while trying to access API.

```
model.findAndCountAll is not a function
TypeError: model.findAndCountAll is not a function
    at getList (/Users/user/Documents/GitHub/jantungku/node_modules/express-sequelize-crud/lib/sequelize/index.js:27:20)
    at /Users/user/Documents/GitHub/jantungku/node_modules/express-sequelize-crud/lib/getList/index.js:32:17
    at Layer.handle [as handle_request] (/Users/user/Documents/GitHub/jantungku/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/user/Documents/GitHub/jantungku/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/user/Documents/GitHub/jantungku/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/user/Documents/GitHub/jantungku/node_modules/express/lib/router/layer.js:95:5)
    at /Users/user/Documents/GitHub/jantungku/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/user/Documents/GitHub/jantungku/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/user/Documents/GitHub/jantungku/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/Users/user/Documents/GitHub/jantungku/node_modules/express-sequelize-crud/node_modules/body-parser/lib/types/json.js:110:7)
```

FYI, my dependencies are:
```
"dependencies": {
    "cookie-parser": "~1.4.4",
    "debug": "~2.6.9",
    "express": "~4.16.1",
    "express-sequelize-crud": "^6.1.2",
    "http-errors": "~1.6.3",
    "jade": "~1.11.0",
    "morgan": "~1.9.1",
    "mysql2": "^2.2.5",
    "sequelize": "^6.3.5",
    "sequelize-auto": "^0.7.6"
  }
```

My code:
```
var { crud, sequelizeCrud } = require('express-sequelize-crud');
var patients = require('./models/patients');

app.use(crud('/admin/patients', sequelizeCrud(patients)))
```

Thank you for your help!

**Comment by nicgirault** [comment]
express-sequelize-crud has a peer dependency to sequelize v5 only. But you can create a connector to v6 as we do here: https://github.com/lalalilo/express-sequelize-crud/blob/master/src/sequelize/index.ts. We might support more sequelize version in a near future.

 Thanks for reporting.
